CGU:
    path:
      en: /Terms_of_use
      fr: /CGU
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template:  'web_site/CGU.html.twig'
        maxAge:    86400
        sharedAge: 86400